import {defaults as streakDefaults} from './digital-streaks/model';
import {renderStreaks} from './digital-streaks/render';
import {defaults as contourDefaults} from './chromatic-contours/model';
import {renderContours} from './chromatic-contours/render';
import {defaults as particleDefaults} from './particle-field/model';
import {renderParticles} from './particle-field/render';
import {defaults as spectralDefaults} from './spectral-bloom/model';
import {renderSpectral} from './spectral-bloom/render';
import {defaults as glassDefaults} from './glass/model';
import {renderGlass} from './glass/render';
import { defaults as fadeDefaults } from './grain-fade/model';
import { renderFade } from './grain-fade/render';
import { defaults as blueprintDefaults } from './blueprint/model';
import { renderBlueprint } from './blueprint/render';
import { defaults as heatedImageDefaults } from './heated-image/model';
import { renderHeated as renderHeatedImage } from './heated-image/render';
import { defaults as sketchDefaults } from './storyboard/model';
import { renderSketch } from './storyboard/render';
import { defaults as toonDefaults } from './toon/model';
import { renderToon } from './toon/render';
import { defaults } from './ascii/model';
import { renderAscii } from './ascii/render';
export const shaders = [{ id: 'ascii', name: 'ASCII', category: 'Character studies', description: 'Every pixel, a different character.', defaults, render: renderAscii }, { id: 'toon', name: 'Painterly Toon', category: 'Paint & ink', description: 'Brushwork meets bold outlines.', defaults: toonDefaults, render: renderToon }, {id:'storyboard',name:'Storyboard Sketch',category:'Pencil & value',description:'A scene, reduced to its essentials.',defaults:sketchDefaults,render:renderSketch}, {id:'heated-image',name:'Heated Shader',category:'Image heat',description:'Your image, glowing from within.',defaults:heatedImageDefaults,render:renderHeatedImage}, {id:'blueprint',name:'Blueprint Mosaic',category:'Grid & symbols',description:'An image, drawn in little details.',defaults:blueprintDefaults,render:renderBlueprint}, {id:'grain-fade',name:'Grain Fade',category:'Soft focus & dissolve',description:'Soften the edges. Let it disappear.',defaults:fadeDefaults,render:renderFade},{id:'glass',name:'Glass Panels',category:'Fluted glass & refraction',description:'Bend an image through sculpted glass.',defaults:glassDefaults,render:renderGlass},{id:'spectral-bloom',name:'Spectral Bloom',category:'Image experiments',description:'',defaults:spectralDefaults,render:renderSpectral},{id:'particle-field',name:'Particle Field',category:'Image experiments',description:'',defaults:particleDefaults,render:renderParticles},{id:'chromatic-contours',name:'Chromatic Contours',category:'Image experiments',description:'',defaults:contourDefaults,render:renderContours},{id:'digital-streaks',name:'Digital Streaks',category:'Image experiments',description:'',defaults:streakDefaults,render:renderStreaks}] as const;
