import { RotateCcw, Shuffle, ChevronDown } from 'lucide-react';
import { defaults, presets, type AsciiParams } from './model';
export function Controls({ params: p, set }: { params: AsciiParams; set: (p: AsciiParams) => void }) {
  const update = <K extends keyof AsciiParams>(key: K, value: AsciiParams[K]) => set({ ...p, [key]: value });
  const slider = (key: keyof AsciiParams, label: string, min: number, max: number, suffix = '%', step = 1) => <label className="slider-control"><span>{label}<output>{p[key]}{suffix}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={Number(p[key])} onChange={e=>update(key, Number(e.target.value))} style={{'--fill':`${(Number(p[key])-min)/(max-min)*100}%`} as React.CSSProperties}/></label>;
  const toggle = (key: 'invert' | 'transparent', label: string) => <label className="toggle-control"><span>{label}</span><input type="checkbox" role="switch" checked={p[key]} onChange={e=>update(key,e.target.checked)}/></label>;
  return <div className="controls"><section className="control-section"><div className="section-title"><span>Characters</span><span className="section-index">01</span></div><label className="field-label">Character set<div className="select-wrap"><select value={p.preset} onChange={e=>set({...p,preset:e.target.value,characters:e.target.value==='Custom'?p.characters:presets[e.target.value]})}>{Object.keys(presets).map(key=><option key={key}>{key}</option>)}</select><ChevronDown size={14}/></div></label><label className="field-label">Custom characters<input className="character-input" maxLength={128} value={p.characters} spellCheck={false} onChange={e=>set({...p,preset:'Custom',characters:e.target.value})}/></label><p className="control-hint">From light to dense. Make it your own.</p>{slider('size','Character size',4,40,' px')}{slider('detail','Detail',40,160)}{slider('coverage','Coverage',0,100)}</section>
  <section className="control-section"><div className="section-title"><span>Appearance</span><span className="section-index">02</span></div><label className="field-label">Character color<div className="segmented"><button className={p.colorMode==='mono'?'active':''} onClick={()=>update('colorMode','mono')}>Single color</button><button className={p.colorMode==='source'?'active':''} onClick={()=>update('colorMode','source')}>From image</button></div></label><div className="color-row"><label><input aria-label="Foreground color" type="color" value={p.foreground} disabled={p.colorMode==='source'} onChange={e=>update('foreground',e.target.value)}/><span>Foreground</span><code>{p.foreground}</code></label></div>{slider('opacity','Character opacity',0,100)}{toggle('invert','Invert tones')}<div className="color-row"><label><input aria-label="Background color" type="color" value={p.background} onChange={e=>update('background',e.target.value)}/><span>Background</span><code>{p.background}</code></label></div>{toggle('transparent','Transparent background')}{slider('original','Original image',0,100)}</section>
  <details className="control-section" open><summary className="section-title"><span>Image adjustments</span><ChevronDown size={14}/></summary>{slider('brightness','Brightness',-100,100)}{slider('contrast','Contrast',-100,100)}{slider('edges','Edge emphasis',0,100)}</details>
  <details className="control-section"><summary className="section-title"><span>Spacing & variation</span><ChevronDown size={14}/></summary>{slider('spacingX','Horizontal spacing',0.6,2,'×',0.05)}{slider('spacingY','Vertical spacing',0.6,2,'×',0.05)}{slider('randomness','Randomness',0,100)}<button className="subtle-button full-width" onClick={()=>update('seed',p.seed+1)}><Shuffle size={14}/> Shuffle characters</button></details><button className="reset-button" onClick={()=>set({...defaults})}><RotateCcw size={14}/> Reset all settings</button></div>;
}
