import { RotateCcw, ChevronDown, Shuffle } from 'lucide-react';
import { defaults, type ToonParams } from './model';
export function Controls({params:p,set}:{params:ToonParams;set:(p:ToonParams)=>void}) {
  const update=<K extends keyof ToonParams>(key:K,value:ToonParams[K])=>set({...p,[key]:value});
  const slider=(key:keyof ToonParams,label:string,min:number,max:number,suffix='%',step=1)=><label className="slider-control"><span>{label}<output>{p[key]}{suffix}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={Number(p[key])} onChange={e=>update(key,Number(e.target.value))} style={{'--fill':`${(Number(p[key])-min)/(max-min)*100}%`} as React.CSSProperties}/></label>;
  const color=(key:'ink'|'background',label:string)=><div className="color-row"><label><input type="color" aria-label={label} value={p[key]} onChange={e=>update(key,e.target.value)}/><span>{label}</span><code>{p[key]}</code></label></div>;
  return <div className="controls"><section className="control-section"><div className="section-title"><span>Brushwork</span><span className="section-index">01</span></div>{slider('paint','Paint amount',0,100)}{slider('brushSize','Brush size',6,48,' px')}{slider('bristles','Bristle texture',0,100)}{slider('variation','Paint variation',0,60)}{slider('flow','Follow contours',0,100)}<button className="subtle-button full-width" onClick={()=>update('seed',p.seed+1)}><Shuffle size={14}/> New brush pattern</button><p className="control-hint">Layered strokes follow the image. Ink stays above the paint.</p></section><section className="control-section"><div className="section-title"><span>Cel shading</span><span className="section-index">02</span></div>{slider('bands','Color bands',2,8,'')}{slider('softness','Surface smoothing',0,8,' px',.5)}<p className="control-hint">Fewer bands create bolder, flatter shapes.</p><label className="field-label">Palette<div className="select-wrap"><select aria-label="Palette" value={p.palette} onChange={e=>update('palette',e.target.value as ToonParams['palette'])}><option value="source">Original colors</option><option value="sunset">Sunset · violet & peach</option><option value="mint">Botanical · teal & cream</option><option value="ink">Graphic · ink & paper</option></select><ChevronDown size={14}/></div></label></section>
  <section className="control-section"><div className="section-title"><span>Ink outlines</span><span className="section-index">03</span></div>{slider('outlines','Outline strength',0,100)}{slider('threshold','Edge threshold',0,80)}{slider('lineWidth','Line width',.5,6,' px',.5)}{color('ink','Ink color')}<p className="control-hint">Raise the threshold to keep only the strongest edges.</p></section>
  <details className="control-section" open><summary className="section-title"><span>Image adjustments</span><ChevronDown size={14}/></summary>{slider('saturation','Saturation',0,200)}{slider('brightness','Brightness',-60,60)}{slider('contrast','Contrast',-60,80)}{slider('original','Original image',0,100)}<label className="toggle-control"><span>Transparent background</span><input type="checkbox" role="switch" checked={p.transparent} onChange={e=>update('transparent',e.target.checked)}/></label>{!p.transparent&&color('background','Background color')}</details><button className="reset-button" onClick={()=>set({...defaults})}><RotateCcw size={14}/> Reset all settings</button></div>;
}
