import {RotateCcw,Shuffle} from 'lucide-react';
import {defaults,type BlueprintParams} from './model';
export function Controls({params:p,set}:{params:BlueprintParams;set:(p:BlueprintParams)=>void}){
 const update=<K extends keyof BlueprintParams>(key:K,value:BlueprintParams[K])=>set({...p,[key]:value});
 const slider=(key:keyof BlueprintParams,label:string,min:number,max:number,suffix='%',step=1)=><label className="slider-control"><span>{label}<output>{p[key]}{suffix}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={Number(p[key])} onChange={e=>update(key,Number(e.target.value))} style={{'--fill':`${(Number(p[key])-min)/(max-min)*100}%`} as React.CSSProperties}/></label>;
 const toggle=(key:'invert'|'transparent',label:string)=><label className="toggle-control"><span>{label}</span><input type="checkbox" role="switch" checked={p[key]} onChange={e=>update(key,e.target.checked)}/></label>;
 const color=(key:'foreground'|'background',label:string)=><div className="color-row"><label><input aria-label={label} type="color" value={p[key]} onChange={e=>update(key,e.target.value)}/><span>{label}</span><code>{p[key]}</code></label></div>;
 return <div className="controls"><section className="control-section"><div className="section-title"><span>Silhouette</span><span className="section-index">01</span></div>{slider('cellSize','Cell size',4,48,' px')}{slider('threshold','Silhouette threshold',0,95)}{toggle('invert','Invert light & dark')}<p className="control-hint">Use a contrasting background or a cutout image. Invert for dark subjects on white.</p>{slider('brightness','Brightness',-60,60)}{slider('contrast','Contrast',-60,80)}</section><section className="control-section"><div className="section-title"><span>Pattern & grid</span><span className="section-index">02</span></div>{slider('patterns','Pattern density',0,100)}{slider('patternScale','Symbol size',20,95)}{slider('lineWidth','Symbol line weight',.5,3,' px',.25)}{slider('grid','Grid visibility',0,60)}<button className="subtle-button full-width" onClick={()=>update('seed',p.seed+1)}><Shuffle size={14}/> Shuffle pattern</button><p className="control-hint">Light becomes dots, midtones become squares, and shadows become crosses and stippling.</p></section><section className="control-section"><div className="section-title"><span>Colors</span></div>{color('foreground','Subject color')}{color('background','Background & ink')}{toggle('transparent','Transparent background')}</section><button className="reset-button" onClick={()=>set({...defaults})}><RotateCcw size={14}/> Reset all settings</button></div>;
}
