import {test,expect} from '@playwright/test';
import fs from 'node:fs';
test('Heated Shapes opens ready, changes form and exports transparent 2x PNG',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:'Open Heated Shapes editor'}).click();const c=page.locator('canvas[aria-label="Heated Shapes image preview"]');await expect.poll(()=>c.evaluate((c:HTMLCanvasElement)=>c.width)).toBe(1600);
 const before=await c.evaluate((c:HTMLCanvasElement)=>c.toDataURL());await page.getByLabel('Shape',{exact:true}).selectOption('ring');await expect.poll(()=>c.evaluate((c:HTMLCanvasElement)=>c.toDataURL())).not.toBe(before);
 await page.getByRole('switch',{name:'Transparent background'}).check();await page.getByLabel('Export scale',{exact:true}).selectOption('2');const event=page.waitForEvent('download');await page.getByRole('button',{name:'Export PNG'}).click();const download=await event;const png=fs.readFileSync((await download.path())!);expect(png.readUInt32BE(16)).toBe(3200);expect(png.readUInt32BE(20)).toBe(2134);
 const pixels=await page.evaluate(async(b64)=>{const image=await createImageBitmap(await(await fetch('data:image/png;base64,'+b64)).blob());const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const x=c.getContext('2d')!;x.drawImage(image,0,0);const data=x.getImageData(0,0,c.width,c.height).data;return {corner:data[3],opaque:data.some((v,i)=>i%4===3&&v===255),color:data.some((v,i)=>i%4===0&&v!==data[i+1])};},png.toString('base64'));expect(pixels.corner).toBe(0);expect(pixels.opaque).toBe(true);expect(pixels.color).toBe(true);
 await page.getByRole('button',{name:'Reset all settings'}).click();await expect(page.getByLabel('Shape',{exact:true})).toHaveValue('capsule');expect(errors).toEqual([]);
});
test('uploaded image selects image heat map and comparison clears on shape change',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Open Heated Shapes editor'}).click();const c=page.locator('canvas[aria-label]');await expect.poll(()=>c.evaluate((c:HTMLCanvasElement)=>c.width)).toBe(1600);await page.getByLabel('Upload image').setInputFiles('public/sample.jpg');await expect(page.getByLabel('Shape',{exact:true})).toHaveValue('image');await page.getByRole('button',{name:'Original',exact:true}).click();await expect(page.getByAltText('Original image for comparison')).toBeVisible();await page.getByLabel('Shape',{exact:true}).selectOption('orb');await expect(page.getByAltText('Original image for comparison')).not.toBeVisible();
});
