import {RotateCcw,ChevronDown,Shuffle} from 'lucide-react';
import {defaults,type SketchParams} from './model';
export function Controls({params:p,set}:{params:SketchParams;set:(p:SketchParams)=>void}){
 const update=<K extends keyof SketchParams>(key:K,value:SketchParams[K])=>set({...p,[key]:value});
 const slider=(key:keyof SketchParams,label:string,min:number,max:number,suffix='%',step=1)=><label className="slider-control"><span>{label}<output>{p[key]}{suffix}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={Number(p[key])} onChange={e=>update(key,Number(e.target.value))} style={{'--fill':`${(Number(p[key])-min)/(max-min)*100}%`} as React.CSSProperties}/></label>;
 const toggle=(key:'crosshatch'|'transparent',label:string)=><label className="toggle-control"><span>{label}</span><input type="checkbox" role="switch" checked={p[key]} onChange={e=>update(key,e.target.checked)}/></label>;
 return <div className="controls"><section className="control-section"><div className="section-title"><span>Pencil lines</span><span className="section-index">01</span></div>{slider('lineStrength','Line strength',0,100)}{slider('lineWidth','Pencil width',.5,5,' px',.5)}{slider('threshold','Edge threshold',0,50)}{slider('roughness','Pencil roughness',0,100)}<p className="control-hint">Loose graphite contours with broken, hand-drawn texture.</p></section>
 <section className="control-section"><div className="section-title"><span>Value & hatching</span><span className="section-index">02</span></div>{slider('shading','Gray wash',0,100)}{slider('levels','Value steps',2,10,'')}{slider('hatching','Hatching strength',0,100)}{slider('spacing','Hatch spacing',3,20,' px')}{slider('angle','Hatch angle',-90,90,'°')}{toggle('crosshatch','Crosshatch shadows')}</section>
 <details className="control-section" open><summary className="section-title"><span>Paper & adjustments</span><ChevronDown size={14}/></summary>{slider('grain','Paper grain',0,100)}{slider('brightness','Brightness',-60,60)}{slider('contrast','Contrast',-60,80)}{toggle('transparent','Transparent paper')}<p className="control-hint">Transparent paper exports only the graphite marks.</p><button className="subtle-button full-width" onClick={()=>update('seed',p.seed+1)}><Shuffle size={14}/> New pencil texture</button></details><button className="reset-button" onClick={()=>set({...defaults})}><RotateCcw size={14}/> Reset all settings</button></div>;
}
