import {useEffect,useRef,useState,type RefObject} from 'react';
import type {GlassParams} from './model';
export function Placement({canvas,params:p,set}:{canvas:RefObject<HTMLCanvasElement|null>;params:GlassParams;set:(p:GlassParams)=>void}){
 const [box,boxSet]=useState({left:0,top:0,width:0,height:0});
 const drag=useRef<{x:number;y:number;position:number;width:number;mode:string}|null>(null);
 useEffect(()=>{const c=canvas.current;if(!c)return;const measure=()=>{const b=c.getBoundingClientRect(),a=c.parentElement!.getBoundingClientRect();boxSet({left:b.left-a.left,top:b.top-a.top,width:b.width,height:b.height});};const o=new ResizeObserver(measure);o.observe(c);o.observe(c.parentElement!);measure();return()=>o.disconnect();},[canvas]);
 const cs=Math.cos(p.angle*Math.PI/180),sn=Math.sin(p.angle*Math.PI/180),span=Math.abs(box.width*cs)+Math.abs(box.height*sn),mid={x:box.width/2,y:box.height/2};
 const line=(value:number)=>{const u=(value/100-.5)*span;return {x:mid.x+u*cs,y:mid.y+u*sn};};
 const start=p.groupPosition-p.groupWidth/2,end=p.groupPosition+p.groupWidth/2,l=line(start),r=line(end),length=Math.hypot(box.width,box.height);
 return <svg className="glass-placement" style={box} viewBox={`0 0 ${box.width} ${box.height}`} aria-label="Glass placement handles" onPointerMove={e=>{const d=drag.current;if(!d)return;const delta=((e.clientX-d.x)*cs+(e.clientY-d.y)*sn)/Math.max(1,span)*100;if(d.mode==='move')set({...p,groupPosition:Math.max(0,Math.min(100,d.position+delta))});else{const left=d.position-d.width/2,right=d.position+d.width/2;const a=d.mode==='left'?Math.max(0,Math.min(right-5,left+delta)):left,b=d.mode==='right'?Math.min(100,Math.max(left+5,right+delta)):right;set({...p,groupPosition:(a+b)/2,groupWidth:Math.min(100,b-a)});}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
 <polygon points={`${l.x-sn*length},${l.y+cs*length} ${r.x-sn*length},${r.y+cs*length} ${r.x+sn*length},${r.y-cs*length} ${l.x+sn*length},${l.y-cs*length}`} fill="#ffffff08" style={{cursor:'move'}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,position:p.groupPosition,width:p.groupWidth,mode:'move'};}}/>
 {[['left',l],['right',r]].map(([mode,point])=>{const a=point as {x:number;y:number};return <g key={mode as string} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,position:p.groupPosition,width:p.groupWidth,mode:mode as string};}} style={{cursor:'ew-resize'}}><line x1={a.x-sn*length} y1={a.y+cs*length} x2={a.x+sn*length} y2={a.y-cs*length} stroke="#ffffff01" strokeWidth="24"/><line x1={a.x-sn*length} y1={a.y+cs*length} x2={a.x+sn*length} y2={a.y-cs*length} stroke="#fff" strokeWidth="1" strokeDasharray="5 5"/><rect x={a.x-5} y={a.y-15} width="10" height="30" fill="#eee" stroke="#111"/></g>;})}</svg>;
}
